import fs from "node:fs";
import path from "node:path";
import { listRepoFiles, readTextFile, resolveRoot } from "../core/files.js";
import { redactSecretLikeText } from "../core/redaction.js";
import { looksLikeN8nWorkflow } from "../scanners/n8n.js";

export interface N8nBackupOptions {
  root: string;
  backupDir: string;
}

export interface N8nBackupReport {
  generatedAt: string;
  root: string;
  backupDir: string;
  files: Array<{
    source: string;
    backup: string;
    redacted: boolean;
  }>;
}

export function backupN8nWorkflows(options: N8nBackupOptions): N8nBackupReport {
  const root = resolveRoot(options.root);
  const backupDir = path.isAbsolute(options.backupDir) ? options.backupDir : path.join(root, options.backupDir);
  const files = [];

  fs.mkdirSync(backupDir, { recursive: true });
  for (const file of listRepoFiles(root)) {
    const text = readTextFile(file);
    if (!text || !looksLikeN8nWorkflow(text, file.relativePath)) continue;
    const redactedText = redactSecretLikeText(text);
    const parsed = parseJson(redactedText);
    const target = path.join(backupDir, file.relativePath.replaceAll("/", "__"));
    fs.writeFileSync(target, parsed ? `${JSON.stringify(parsed, null, 2)}\n` : redactedText, "utf8");
    files.push({
      source: file.relativePath,
      backup: path.relative(root, target).replaceAll("\\", "/"),
      redacted: redactedText !== text
    });
  }

  fs.writeFileSync(path.join(backupDir, "README.md"), [
    "# n8n Workflow Backup",
    "",
    "This directory is generated by Agent Reliability Kit.",
    "",
    "- Workflow JSON is formatted for Git review.",
    "- Token-like values are redacted before writing.",
    "- Review every public webhook, code node, and command execution node before sharing.",
    ""
  ].join("\n"), "utf8");

  const report: N8nBackupReport = {
    generatedAt: new Date().toISOString(),
    root,
    backupDir: path.relative(root, backupDir).replaceAll("\\", "/"),
    files
  };
  fs.writeFileSync(path.join(backupDir, "backup-report.json"), JSON.stringify(report, null, 2), "utf8");
  return report;
}

function parseJson(text: string): unknown | null {
  try {
    return JSON.parse(text) as unknown;
  } catch {
    return null;
  }
}
