import fs from "node:fs";
import path from "node:path";
import { listRepoFiles, readTextFile, resolveRoot } from "../core/files.js";
import { redactSecretLikeText } from "../core/redaction.js";
import { looksLikeN8nWorkflow } from "../scanners/n8n.js";

export interface N8nBackupOptions {
  root: string;
  backupDir: string;
}

export interface N8nBackupReport {
  generatedAt: string;
  root: string;
  backupDir: string;
  files: Array<{
    source: string;
    backup: string;
    redacted: boolean;
  }>;
}

export function backupN8nWorkflows(options: N8nBackupOptions): N8nBackupReport {
  const root = resolveRoot(options.root);
  const backupDir = path.resolve(root, options.backupDir);
  const files = [];
  const physicalRoot = fs.realpathSync(root);
  const physicalOutput = resolvePhysicalPath(backupDir);
  if (isInside(physicalOutput, physicalRoot)) throw new Error("Backup output must not be the repository root or its ancestor.");
  const candidates = [];
  // Portable backups must also be safe on case-insensitive macOS volumes.
  const destinationKey = (target: string): string => target.toLowerCase();
  const destinations = new Set(["README.md", "backup-report.json"].map((name) => destinationKey(path.join(backupDir, name))));

  for (const file of listRepoFiles(root)) {
    if (isInside(physicalOutput, path.resolve(physicalRoot, file.relativePath))) continue;
    const text = readTextFile(file);
    if (!text || !looksLikeN8nWorkflow(text, file.relativePath)) continue;
    const redactedText = redactSecretLikeText(text);
    const parsed = parseJson(redactedText);
    const target = path.join(backupDir, file.relativePath.replaceAll("/", "__"));
    const key = destinationKey(target);
    if (destinations.has(key)) throw new Error("Workflow backup filenames collide after path flattening. Rename the source paths and retry.");
    destinations.add(key);
    candidates.push({ file, text, redactedText, parsed, target });
  }

  fs.mkdirSync(backupDir, { recursive: true });
  for (const { file, text, redactedText, parsed, target } of candidates) {
    fs.writeFileSync(target, parsed ? `${JSON.stringify(parsed, null, 2)}\n` : redactedText, "utf8");
    files.push({
      source: file.relativePath,
      backup: path.relative(root, target).replaceAll("\\", "/"),
      redacted: redactedText !== text
    });
  }

  fs.writeFileSync(path.join(backupDir, "README.md"), [
    "# n8n Workflow Backup",
    "",
    "This directory is generated by Agent Reliability Kit.",
    "",
    "- Workflow JSON is formatted for Git review.",
    "- Token-like values are redacted before writing.",
    "- Review every public webhook, code node, and command execution node before sharing.",
    ""
  ].join("\n"), "utf8");

  const report: N8nBackupReport = {
    generatedAt: new Date().toISOString(),
    root,
    backupDir: path.relative(root, backupDir).replaceAll("\\", "/"),
    files
  };
  fs.writeFileSync(path.join(backupDir, "backup-report.json"), JSON.stringify(report, null, 2), "utf8");
  return report;
}

function isInside(directory: string, candidate: string): boolean {
  const relative = path.relative(directory, candidate);
  return relative === "" || (relative !== ".." && !relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative));
}

function resolvePhysicalPath(directory: string): string {
  if (fs.existsSync(directory)) return fs.realpathSync(directory);
  const parent = path.dirname(directory);
  if (parent === directory) throw new Error("Backup destination parent is unavailable.");
  return path.join(resolvePhysicalPath(parent), path.basename(directory));
}

function parseJson(text: string): unknown | null {
  try {
    return JSON.parse(text) as unknown;
  } catch {
    return null;
  }
}
